### ISSUE TITLE
use this for scroll

### ISSUE THREAD

**Issue by sohzm** [cynthwave/wisk#64]
```css
@media (hover: hover) {
    *::-webkit-scrollbar { width: 15px; }
    *::-webkit-scrollbar-track { background: var(--bg-1); }
    *::-webkit-scrollbar-thumb { background-color: var(--bg-3); border-radius: 20px; border: 4px solid var(--bg-1); }
    *::-webkit-scrollbar-thumb:hover { background-color: var(--text-1); }
}
```
